### ISSUE TITLE
Expert data

### ISSUE THREAD

**Issue by NathanGavenski** [rahulkidambi/MobILE-NeurIPS2021#2]
Hi guys, sorry for bothering you again. I'm really glad you guys released the code! But I cant seem to find an example of your expert data structure. Would you be able to upload just a short example?

**Comment by jdchang1** [comment]
Hey Nathan no problem at all! All of the data processing is in the `mbil/utils/utils.py` script. Here is the structure that we expect

Dataset: List of dictionaries
Each dictionary has keys `episode` and `ep_rew`
episode: tuple of 5 arrays (states, actions, next_states, rewards, is_terminal)

Of course we don't need to use actions for the algorithm but just included it in the dataset. So for example an expert dataset of 10 trajectories would be a list of 10 dictionaries with each dictionary containing the episode represented as a tuple and the episode reward. 

Feel free to modify reading in your own data format. Specifically check out `get_db_mjrl()` on line 126 of `utils.py`. Hope this helps!

**Comment by jdchang1** [comment]
Also if you check out https://github.com/jdchang1/milo, there is a google drive link in the readme that should direct you to the expert data.

**Comment by NathanGavenski** [comment]
Thanks for answering in such a short time. 

I'm thinking of using stable_baselines expert, so modifying the original `.npz` file will be easy with the explanation and example.
